### ISSUE TITLE
Sql file issue

### ISSUE THREAD

**Issue by deysuman** [somratcste/hospital-management-system#2]
Where is your sql file?

**Comment by somratcste** [comment]
laravel does not provide any sql file . If you want to run with database firstly you can create a database and then configure in .env file then run laravel artisan command 
php artisan migrate 
I think you can find your database with table and column :) @deysuman

**Comment by deysuman** [comment]
Column not found: 1054 Unknown column 'due' in 'where clause' error

**Comment by deysuman** [comment]
Login not working in laravel
