### ISSUE TITLE
Unable to login locally as super user

### ISSUE THREAD

**Issue by hydeenoble** [somratcste/hospital-management-system#4]
How do I login as a super user?

**Comment by somratcste** [comment]
may be you need to make a user seeder then i think work properly.

**Comment by hydeenoble** [comment]
I can't find any UserSeeder In the project, is there a way I can get it or I have to create mine?

**Comment by somratcste** [comment]
Yes,,, you can create new one for yours just check which attribute are required for making a new user seeder :)
