### ISSUE TITLE
Can I have your email pls

### ISSUE THREAD

**Issue by 3plehbeats** [somratcste/hospital-management-system#7]
I am a beginner coder in php. Is this a laravel project. Kindly explain what you did. I'll like to be able to develop portals and management systems. Thanks My Whatsapp number is +2348146339854

**Comment by somratcste** [comment]
You will be understand. First you need to travel with all modules and plan.
Then try to design your database after analyse your client requirement.
Hope for the best.

**Comment by 3plehbeats** [comment]
Hello man please can you be my mentor in web application development . I

**Comment by 3plehbeats** [comment]
Hello man please can you be my mentor in web application development . I am
a computer science graduate but I have basic skills in front end
development.

I am interested in bootstrap, javascript, jquery and php.. Kindly contact
me on whatsapp +2348146339854. I am Tunde by name from Africa

Regards,
Tunde
